### ISSUE TITLE
add license in readme

### ISSUE THREAD

**Issue by Parikshit-Hooda** [devfolioco/devfolio-gatsby-starter#26]
Add the LICENSE section in the readme.md file.

**Comment by vidhigupta9** [comment]
I can help with this. what are your expectations exactly?

**Comment by Snaked06** [comment]
hey @Parikshit-Hooda @vidhigupta9 would love to work on this issue , can you do elaborate the problem once

**Comment by Parikshit-Hooda** [comment]
Hey @alvesgabriel, I think I should raise a PR as I found the issue.

**Comment by Parikshit-Hooda** [comment]
@ajayns Your decision is final. That being said, I hope you root for me! 👍

**Comment by alvesgabriel** [comment]
@Parikshit-Hooda, I'm sorry. I think you only was reporting the task. The PR is close now.

**Comment by iamrajiv** [comment]
@apollonian Can I work on this issue?
