### ISSUE TITLE
Improve Accessibility by labelling content with text 

### ISSUE THREAD

**Issue by itaditya** [devfolioco/devfolio-gatsby-starter#37]
Important Images like Logo and Sponsor Images don't have proper text labels. They should be added so people who start their projects with this starter have a solid base and they themselves don't have to fix these issues themselves in their own project

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/15871340/66307228-853beb80-e921-11e9-8756-22c9ae23f32b.png">

**Comment by sagarchoudhary96** [comment]
@itaditya can i take it up ?

**Comment by itaditya** [comment]
@sagarchoudhary96 I was hoping to work on this issue myself. I'm just waiting for the maintainers to give me a go-ahead.

**Comment by sagarchoudhary96** [comment]
ohh okay you go ahead with this 👍

**Comment by itaditya** [comment]
@ajayns can you review my PR regarding this https://github.com/devfolioco/devfolio-gatsby-starter/pull/40
