### ISSUE TITLE
Can anyone help me installing the dependencies?

### ISSUE THREAD

**Issue by rahulatrkm** [devfolioco/devfolio-gatsby-starter#44]
I was installing the dependencies of this project by following the instructions given here. But seems like my laptop has hang there. Can anyone tell me what could be the problem here?

![Screenshot from 2019-10-13 16-42-45](https://user-images.githubusercontent.com/25795515/66714759-90d35a80-edd8-11e9-9c6a-3f8f021ffb86.png)

**Comment by SatyaRF** [comment]
Hi Rahul,
Sometimes gatsby starter site does not open in your default browser automatically. I think there is no problem with your installation. Try copy pasting the link and it should work fine.
Happy Coding!!
Satya
