### ISSUE TITLE
Make Devfolio logo clickable

### ISSUE THREAD

**Issue by ShreyaPanale** [devfolioco/devfolio-gatsby-starter#77]
It should link back to homepage

**Comment by sahastrakishore123** [comment]
I would like to do this as a part of Hacktoberfest. Can you assign me to do so? @ShreyaPanale

**Comment by vsasvipul0605** [comment]
I want to work on this. please assign this to me.

**Comment by Dhruv-VINT** [comment]
Looks like a good first issue to me, would love to contribute on this !
