### ISSUE TITLE
Add key props

### ISSUE THREAD

**Issue by harshil1712** [devfolioco/devfolio-gatsby-starter#8]
![Screenshot from 2019-10-03 15-23-04](https://user-images.githubusercontent.com/18901032/66117883-d2068600-e5f2-11e9-9208-fb287f9008f4.png)
The above error is consoled in the dev tools. Although this is not creating any negative effect, it is always good to follow best practices.

**Comment by apollonian** [comment]
Thanks. Fixed with #9. Closing the issue.
