### ISSUE TITLE
Adding Dark Mode to 'Gatsby Landing Starter' Page

### ISSUE THREAD

**Issue by manishkrjha** [devfolioco/devfolio-gatsby-starter#99]
Presently <a href="http://devfolio-gatsby-starter.surge.sh/">Gatsby Landing Starter</a> page is in light mode only. I propose adding a toggle button that gives users the option to switch between ***light*** and ***dark*** mode.

**Comment by the-supernova** [comment]
I am interested in working with this issue

**Comment by manishkrjha** [comment]
@the-supernova since I have opened this so I guess it's pretty obvious that even I am interested in this 😅

**Comment by apollonian** [comment]
@manishkrjha Sure, please go ahead!

**Comment by manishkrjha** [comment]
Thanks, can you please provide to path/directory to the HTML CSS and JS files for this page?

Thank you.

**Comment by subhamX** [comment]
@manishkrjha this project is using `gatsby` and all assets, components are inside the `src/` directory. In case you are no longer working on this or need any help in some part please do share with us.

**Comment by subhamX** [comment]
@manishkrjha this project is using `gatsby` and almost all things which we need to add the dark mode lies inside the `src/` directory. In case you are no longer working on this or need any help in some part please do share with us.

**Comment by manishkrjha** [comment]
Sorry, I won't be able to work on it now
